{% set version = "1.9.1" %}

package:
  name: jsoncpp
  version: {{ version }}

source:
  url: https://github.com/open-source-parsers/jsoncpp/archive/{{ version }}.tar.gz
  sha256: c7b40f5605dd972108f503f031b20186f5e5bca2b65cd4b8bd6c3e4ba8126697

build:
  number: 0
  skip: true  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage('jsoncpp', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler("cxx") }}
    - cmake
    - make        # [unix]
    - pkg-config  # [unix]
    - python

test:
  commands:
    # Verify headers are present.
    - test -f "${PREFIX}/include/json/json.h"                       # [unix]
    - if not exist %PREFIX%\\Library\\include\\json\\json.h exit 1  # [win]

    # Verify pkg-config file is present.
    - test -f "${PREFIX}/lib/pkgconfig/jsoncpp.pc"  # [unix]

    # Verify libraries are present.
    - test -f "${PREFIX}/lib/libjsoncpp.a"  # [unix]
    - python -c "import ctypes; ctypes.cdll[r'${PREFIX}/lib/libjsoncpp${SHLIB_EXT}']"  # [unix]
    - if not exist %PREFIX%\\Library\\lib\\jsoncpp.lib exit 1                          # [win]
  requires:
    - python

about:
  home: https://github.com/open-source-parsers/jsoncpp
  license: Public Domain/MIT
  license_file: LICENSE
  summary: A C++ library for interacting with JSON.

extra:
  recipe-maintainers:
    - jakirkham
    - stuarteberg
    - marcelotrevisani
