travis:
  secure:
    BINSTAR_TOKEN: EVH5ZsbJtNCenkBoDNc/v2s3y2y2bGhf+01bceGgUyk9Wy/rdb7u0h5Xryd2dcWbTNQ+hOUkxOUQexomDG73CdnQFgymlr7PN7c0ltLOiD3koPIliuUk7T73vnmo36px4tow2089l2ulWxsF9JyqjX79Ez1ET2+qpU7VGObgSiHO3HR3O8RaP6vWpAkpxkOQIVWmoAjPRZIvwY7+vqNUqrptDCrsv0cBL3A+1+2lZWzJ6Tzy0g66xUNe/pmpg7u9l6EzkShnS+EEB6/97exYDVx8n6/UMPEfxW1GoIel4lPChXivOlSliCbmGwdUtHynP0jJpBxGfNF2xFg3ZFzGHVApFc3TbJ85HEw6MnK2eGmWegzpVMrE1oj4GkYDOThHVyakB9Ccq8r3fKKT7L29+XFLjS2qf21OxM0/ZOq5na3kksK0EqHw6LXUdknMhFYiKROMvdtpCRT1g0Vu6NqwKQFrUzdiMGU1deCGj18b6uWLhmHVlL2iMJG3tVIA9KculOEGKjbOYqYjr+d5aVpFOiOX4Y7XE9kI5KCGigC92dfBELdJH7/XjKBFFuMQKonbkHylWy/Twbtzf/vgW+V+q4O8RE+GKfI1AphKuhBknvoINVh0YlREhrj9tjhZRPfWjKPjEswvWgpEkN88wiDl885KXeb1HJKtgkmaiYO2+M8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
